"""initial merchant and audit

Revision ID: 543da07c5ff1
Revises: 
Create Date: 2026-07-21 22:17:58.583983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543da07c5ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('telegram_first_name', sa.String(length=255), nullable=False),
    sa.Column('telegram_last_name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('telebirr_name', sa.String(length=255), nullable=False),
    sa.Column('telebirr_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('REGISTERING', 'REGISTERED', name='merchant_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_merchants_business_email'), 'merchants', ['business_email'], unique=True)
    op.create_index(op.f('ix_merchants_telebirr_phone'), 'merchants', ['telebirr_phone'], unique=True)
    op.create_index(op.f('ix_merchants_telegram_id'), 'merchants', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchants_telegram_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_telebirr_phone'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_business_email'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
